version: '3'

services:
  squid3:
    image: sameersbn/squid:3.3.8-23
    ports:
      - 3128:3128
    networks:
      - bridge
    volumes:
      - /persistent/squid3/cache:/var/spool/squid3
      - /persistent/squid3/log:/var/log/squid3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  bridge:
