version: '3.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=home-cl
      - bootstrap.memory_lock=false
      - "action.auto_create_index=.security,.monitoring*,.watches,.triggered_watches,.watcher-history*"
      - "action.destructive_requires_name=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /persistent/elk/elasticsearch:/usr/share/elasticsearch/config
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.1
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /persistent/elk/kibana:/usr/share/kibana/config
    ports:
      - 5601:5601
    networks:
      - esnet
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.10.1
    container_name: logstash
    environment:
      - SERVER_NAME=logstash
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - http.port=9600
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /persistent/elk/logstash:/usr/share/logstash/config
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - esnet
  heartbeat:
    image: docker.elastic.co/beats/heartbeat-oss:7.10.1
    container_name: heartbeat
    environment:
      - SERVER_NAME=heartbeat
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /persistent/elk/heartbeat:/usr/share/heartbeat/config
    networks:
      - esnet
  metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:7.10.1
    container_name: metricbeat
    environment:
      - SERVER_NAME=metricbeat
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /persistent/elk/metricbeat:/usr/share/metricbeat/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - esnet
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.10.1
    container_name: filebeat
    environment:
      - SERVER_NAME=filebeat
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /persistent/elk/filebeat:/usr/share/filebeat/config
      - /var/lib/docker/containers:/usr/share/filebeat/dockerlogs:ro
    networks:
      - esnet
  packetbeat:
    image: docker.elastic.co/beats/packetbeat-oss:7.10.1
    container_name: packetbeat
    cap_add:
      - NET_ADMIN
    environment:
      - SERVER_NAME=packetbeat
<<<<<<< Updated upstream
      #- ELASTICSEARCH_URL=http://elasticsearch:9200
=======
      - ELASTICSEARCH_URL=http://elasticsearch:9200
>>>>>>> Stashed changes
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 0
      #placement:
      #  constraints: [node.role == manager]
      - /persistent/elk/packetbeat:/usr/share/packetbeat/config
    networks:
      - esnet
      
volumes:
  elastic_data:
    driver: local

networks:
  esnet:
